export enum TypeNoti {
  // Account related
  ACCOUNT_REGISTER_SUCCESS = 'ACCOUNT_REGISTER_SUCCESS',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS',
  PASSWORD_CHANGED_SUCCESS = 'PASSWORD_CHANGED_SUCCESS',
  ACCOUNT_UPDATED_SUCCESS = 'ACCOUNT_UPDATED_SUCCESS',

  // Appointment related
  APPOINTMENT_BOOKED = 'APPOINTMENT_BOOKED',
  APPOINTMENT_CONFIRMED = 'APPOINTMENT_CONFIRMED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',

  // Question/Answer related
  QUESTION_SUBMITTED = 'QUESTION_SUBMITTED',
  YoutubeED = 'YoutubeED',

  // General
  GENERAL_INFO = 'GENERAL_INFO'
}
