export enum TypeNoti {
  CREATE_ACCOUNT = 'CREATE_ACCOUNT',
  CONSULT_APPOINTMENT = 'CONSULT_APPOINTMENT',
  LABORATORY_APPOINTMENT = 'LABORATORY_APPOINTMENT',
  BLOG = 'BLOG',
  FEEDBACK = 'FEEDBACK',
  TRANSACTION = 'TRANSACTION'
}
